name: Test Build

on:
  workflow_dispatch:

jobs:
  test-build:
    strategy:
      fail-fast: false
      matrix:
        ncs_version: ["v2.7.0", "v2.8.0", "v2.9.0"]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run integration-test ${{ matrix.ncs_version }}
